import {inter, sfPro} from '../fonts';
import cx from 'classnames';
import '../styles/globals.css';
import Nav from '@/components/layout/nav';
import Navbar from '@/components/layout/nav-bar';
import NavbarMobile from '@/components/layout/nav-bar-mobile';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={cx(sfPro.variable, inter.variable)}>
        <div className="fixed h-screen w-full bg-gradient-to-br from-indigo-50 via-white to-cyan-100" />
        {/* <Suspense fallback="..."> */}
        <NavbarMobile />
        <Navbar />
        {/* </Suspense> */}
        <main className="relative flex min-h-screen w-full flex-col items-center justify-center py-32 px-3">
          {children}
        </main>
        {/* <Footer />
        <Analytics /> */}
      </body>
    </html>
  );
}
